Numpy

In [1]:
import numpy as np

In [6]:
big_list = list(range(100000))
big_array =  np.arange(100000)

In [7]:
%timeit [x ** 2 for x in big_list]

30.8 ms ± 3.41 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
%timeit big_array ** 2

480 μs ± 27.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [9]:
###creating array 

In [10]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [12]:
a = np.array([0,0,0,0])
print(a)

[0 0 0 0]


In [16]:
zero = np.zeros((2,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [18]:
print(np.full((2,3),7))

[[7 7 7]
 [7 7 7]]


In [19]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [20]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
rng = np.random.default_rng(seed=42)
print(rng.random((2,3)))

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]


In [25]:
print(rng.integers(1,10,size=(3,3)))

[[7 7 7]
 [8 5 2]
 [8 5 5]]


In [27]:
print(rng.normal(loc=0,scale=1,size=5))

[ 0.77779194  0.0660307   1.12724121  0.46750934 -0.85929246]


In [28]:
###array atttributes and data types

In [30]:
M = np.array([[1,2,3],[4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
print(M.ndim)

2


In [32]:
print(M.shape)

(2, 3)


In [33]:
print(M.dtype)

int64


In [34]:
print(M.size)

6


In [35]:
ints = np.array([1,2,3])

In [36]:
ints.dtype

dtype('int64')

In [37]:
ints = np.array([1,2,3],dtype = np.int32)

In [38]:
ints.dtype

dtype('int32')

In [40]:
floats = np.array([1,2,3],dtype = np.float64)
floats.dtype

dtype('float64')

In [41]:
#indexing and slicing

In [42]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [43]:
print(x[0])

10


In [44]:
print(x[5])

15


In [45]:
M = np.arange(1,13).reshape(3,4)
M

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
print(M[1,2])

7


In [47]:
M[1]

array([5, 6, 7, 8])

In [48]:
print(M[:,1])

[ 2  6 10]


In [49]:
print(M[:,0])

[1 5 9]


In [50]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
print(a)

[1 2 3 4]


In [51]:
print(b)

[10 20 30 40]


In [52]:
print(a+b)

[11 22 33 44]


In [53]:
print(a*b)

[ 10  40  90 160]


In [54]:
a = np.array([1,2,3])
b = 10

In [55]:
print(a+b)

[11 12 13]


In [56]:
a = np.array([[1,2,3],
              [4,5,6]])  
a.shape

(2, 3)

In [57]:
b = np.array([10,20,30])
b.shape

(3,)

In [58]:
print(a+b)

[[11 22 33]
 [14 25 36]]
